### ISSUE TITLE
How to get the "real" TouchID dialog with "enter password" option?

### ISSUE THREAD

**Issue by caspahouzer** [appcelerator-modules/ti.touchid#15]

**Comment by hansemannn** [comment]
Did you check this one here: http://stackoverflow.com/questions/30294479/show-enter-password-for-touch-id-authentication

**Comment by caspahouzer** [comment]
+++++1

- Sebastian 

Sent from my iPhone

**Comment by zenoyu** [comment]
Are there any chance to allow enter by `Pass Code` after 3 times Touch ID failed?

**Comment by hansemannn** [comment]
From what we currently know, Apple did not expose that functionality, yet. If you find something natively, let me know and we can implement it.

**Comment by caspahouzer** [comment]
Because Apple does not provide this functionality, I decided to code it myself. 

The disadvantage is, that the user has to enter a new personal code within the app.

See a demo here: https://github.com/caspahouzer/TiPasscode

**Comment by zenoyu** [comment]
That is great @caspahouzer Thanks :)
